### PR TITLE
[wrt] update ca-certificates package to version 20160104

### PR DESCRIPTION
**Pull request by shmick**

### CODE REVIEW

**Comment by CapnBry** [comment]
Thanks, Steve! After I do v13 release this week my 50% goal is to port everything to the latest OpenWrt so we'll get a few years before we start losing packages all the time like this. Is there a better way to have HTTPS support with curl without constantly updating root certs URLs?

**Comment by shmick** [comment]
Not really. Could always throw in a schedule task on boot to run something like 
```curl https://curl.haxx.se/ca/cacert.pem -o /path/to/ca-bundle.crt``` which is only about 250KB

**Comment by shmick** [comment]
Aaaaand is looks like svn.openwrt.org has gone dark. Should probably have a copy of 12.09 r36422 sitting on github that can be easily cloned. I kept meaning to do this...

**Comment by shmick** [comment]
This looks to work ok and you end up on r36423 vs r36422
```
git clone git://git.openwrt.org/12.09/openwrt.git openwrt
cd openwrt
git checkout f83d737
```

From ```git log```
```
commit f83d737d3ece14a41782615ae068e328df909ac8
Author: jow <jow@3c298f89-4303-0410-b956-a3cf2f4a3e73>
Date:   Thu Apr 25 09:36:00 2013 +0000

    AA: base-files: backport r36107
    
    
    git-svn-id: svn://svn.openwrt.org/openwrt/branches/attitude_adjustment@36423 3c298f89-4303-0410-b956-a3cf2f4a3e73
```

**Pull request merged**
